export const ALL_USERS = gql`
    {
        users{
            users{
                _id
                username
                email
                games{
                  name
                  cover
                  rating
                  condition
                  platform
                  price
                }
            }
        }
    }
`;